# 실제 서버로 들어가게될 docker compose file
services:
  spring:
    image: ${ECR_URI}
    container_name: auction-spring
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}

      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

  redis:
    image: redis:8.6.2
    container_name: auction-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

